name: Build App

on:
  workflow_run:
    workflows: ["Precommit"]
    types:
      - completed


jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          echo "Building the App..."
