name: Call Publish Workflow

on:
  pull_request:
    branches:
      - main  # Runs only on push (merge) to main

jobs:
  call-publish:
    uses: splunk-soar-connectors/.github/.github/workflows/publish.yml@tapishj/PAPP-35446
