name: Call Publish Workflow

on:
  push:
    branches:
      - main  # Runs only on push (merge) to main
      - mnordby/test #remove

jobs:
  call-publish:
    uses: splunk-soar-connectors/.github/.github/workflows/publish.yml@mnordby/PAPP-35411
    with:
      GITHUB_TOKEN: ${{ secrets.SOAR_APPS_GITHUB_KEY }}